"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import createdreversal as shared_createdreversal
from ..shared import createreversal as shared_createreversal
from ..shared import error as shared_error
from typing import Optional



@dataclasses.dataclass
class CancelTransferRequest:
    transfer_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'transferID', 'style': 'simple', 'explode': False }})
    r"""ID of the Transfer"""
    x_idempotency_key: str = dataclasses.field(metadata={'header': { 'field_name': 'X-Idempotency-Key', 'style': 'simple', 'explode': False }})
    r"""Prevents duplicate reversals from being created"""
    create_reversal: Optional[shared_createreversal.CreateReversal] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class CancelTransferResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    created_reversal: Optional[shared_createdreversal.CreatedReversal] = dataclasses.field(default=None)
    r"""Successfully initiated a reversal"""
    error: Optional[shared_error.Error] = dataclasses.field(default=None)
    r"""Reversal request failed, an error message will be available in the response body."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

