"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import applepaymerchantdomains as shared_applepaymerchantdomains
from typing import Optional



@dataclasses.dataclass
class GetApplePayMerchantDomainsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    




@dataclasses.dataclass
class GetApplePayMerchantDomainsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    apple_pay_merchant_domains: Optional[shared_applepaymerchantdomains.ApplePayMerchantDomains] = dataclasses.field(default=None)
    r"""Domains registered with Apple Pay"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

