"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import countries as shared_countries
from typing import Optional



@dataclasses.dataclass
class GetAccountCountriesRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    




@dataclasses.dataclass
class GetAccountCountriesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    countries: Optional[shared_countries.Countries] = dataclasses.field(default=None)
    r"""The Requested Countries"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

