"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import enrichmentprofile as shared_enrichmentprofile
from typing import Optional



@dataclasses.dataclass
class GetEnrichmentProfileRequest:
    email: str = dataclasses.field(metadata={'query_param': { 'field_name': 'email', 'style': 'form', 'explode': True }})
    r"""Valid email address belonging to the profile of interest"""
    




@dataclasses.dataclass
class GetEnrichmentProfileResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    enrichment_profile: Optional[shared_enrichmentprofile.EnrichmentProfile] = dataclasses.field(default=None)
    r"""The enriched profile"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

