"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import fullissuedcard as shared_fullissuedcard
from typing import Optional



@dataclasses.dataclass
class GetFullIssuedCardRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    issued_card_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'issuedCardID', 'style': 'simple', 'explode': False }})
    r"""ID of the issued card"""
    




@dataclasses.dataclass
class GetFullIssuedCardResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    full_issued_card: Optional[shared_fullissuedcard.FullIssuedCard] = dataclasses.field(default=None)
    r"""Successfully retrieved card details"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

