"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import card as shared_card
from typing import Optional



@dataclasses.dataclass
class GetListCardsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    




@dataclasses.dataclass
class GetListCardsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    cards: Optional[list[shared_card.Card]] = dataclasses.field(default=None)
    r"""Successfully retrieved cards"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

