"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import networkids as shared_networkids
from typing import Optional



@dataclasses.dataclass
class GetNetworkIDsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    




@dataclasses.dataclass
class GetNetworkIDsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    network_i_ds: Optional[shared_networkids.NetworkIDs] = dataclasses.field(default=None)
    r"""The network IDs of the account"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

