"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bankaccountresponse as shared_bankaccountresponse
from typing import Any, Optional



@dataclasses.dataclass
class LinkBankAccountRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    request_body: Any = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class LinkBankAccountResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bank_account_response: Optional[shared_bankaccountresponse.BankAccountResponse] = dataclasses.field(default=None)
    r"""Bank account added"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

