"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import industries as shared_industries
from typing import Optional



@dataclasses.dataclass
class ListIndustriesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    industries: Optional[shared_industries.Industries] = dataclasses.field(default=None)
    r"""A list of industries and their codes"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

