"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bankaccountresponse as shared_bankaccountresponse
from typing import Optional



@dataclasses.dataclass
class ListBankAccountsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    




@dataclasses.dataclass
class ListBankAccountsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bank_accounts: Optional[list[shared_bankaccountresponse.BankAccountResponse]] = dataclasses.field(default=None)
    r"""Successfully retrieved bank accounts"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

