"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import gettransferfull as shared_gettransferfull
from ..shared import patchtransfer as shared_patchtransfer
from typing import Optional



@dataclasses.dataclass
class PatchTransferRequest:
    patch_transfer: shared_patchtransfer.PatchTransfer = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    transfer_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'transferID', 'style': 'simple', 'explode': False }})
    r"""ID of the Transfer"""
    account_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'accountID', 'style': 'form', 'explode': True }})
    r"""ID of a connected account"""
    




@dataclasses.dataclass
class PatchTransferResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_transfer_full: Optional[shared_gettransferfull.GetTransferFull] = dataclasses.field(default=None)
    r"""Details of a transfer"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

