"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import patchrepresentativerequest as shared_patchrepresentativerequest
from ..shared import representative as shared_representative
from typing import Optional



@dataclasses.dataclass
class PatchRepresentativeRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    patch_representative_request: shared_patchrepresentativerequest.PatchRepresentativeRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    representative_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'representativeID', 'style': 'simple', 'explode': False }})
    r"""ID of the representative"""
    




@dataclasses.dataclass
class PatchRepresentativeResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    representative: Optional[shared_representative.Representative] = dataclasses.field(default=None)
    r"""representative patched"""
    

