"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import account as shared_account
from ..shared import patchaccountrequest as shared_patchaccountrequest
from typing import Optional



@dataclasses.dataclass
class PatchAccountRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    patch_account_request: shared_patchaccountrequest.PatchAccountRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PatchAccountResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    account: Optional[shared_account.Account] = dataclasses.field(default=None)
    r"""The patched account"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

