"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import linkapplepay as shared_linkapplepay
from ..shared import linkedapplepaypaymentmethod as shared_linkedapplepaypaymentmethod
from typing import Optional



@dataclasses.dataclass
class PostLinkApplePayTokenRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    link_apple_pay: shared_linkapplepay.LinkApplePay = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PostLinkApplePayTokenResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    linked_apple_pay_payment_method: Optional[shared_linkedapplepaypaymentmethod.LinkedApplePayPaymentMethod] = dataclasses.field(default=None)
    r"""Apple Pay token linked"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

