"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import createapplepaysession as shared_createapplepaysession
from typing import Any, Optional



@dataclasses.dataclass
class PostApplePaySessionRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    create_apple_pay_session: shared_createapplepaysession.CreateApplePaySession = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PostApplePaySessionResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    apple_pay_session: Optional[Any] = dataclasses.field(default=None)
    r"""Session created with Apple Pay"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

