"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import issuedcard as shared_issuedcard
from ..shared import requestcard as shared_requestcard
from typing import Optional



@dataclasses.dataclass
class PostRequestCardRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    request_card: shared_requestcard.RequestCard = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PostRequestCardResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    issued_card: Optional[shared_issuedcard.IssuedCard] = dataclasses.field(default=None)
    r"""Card created"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

