"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import completemicrodepositsrequest as shared_completemicrodepositsrequest
from ..shared import completemicrodepositsresponse as shared_completemicrodepositsresponse
from typing import Optional



@dataclasses.dataclass
class PutCompleteMicroDepositsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    bank_account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'bankAccountID', 'style': 'simple', 'explode': False }})
    r"""ID of the bank account"""
    complete_micro_deposits_request: shared_completemicrodepositsrequest.CompleteMicroDepositsRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PutCompleteMicroDepositsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    complete_micro_deposits_response: Optional[shared_completemicrodepositsresponse.CompleteMicroDepositsResponse] = dataclasses.field(default=None)
    r"""Micro-Deposits Successfully verified"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

