"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import financialinstitutions as shared_financialinstitutions
from ..shared import rail as shared_rail
from typing import Optional



@dataclasses.dataclass
class SearchInstitutionsRequest:
    rail: shared_rail.Rail = dataclasses.field(metadata={'path_param': { 'field_name': 'rail', 'style': 'simple', 'explode': False }})
    r"""Payment rail to search on"""
    limit: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    r"""Maximum results returned by a search"""
    name: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'name', 'style': 'form', 'explode': True }})
    r"""Name of the financial institution"""
    routing_number: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'routingNumber', 'style': 'form', 'explode': True }})
    r"""Routing number for a financial institution"""
    state: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'state', 'style': 'form', 'explode': True }})
    r"""Optional parameters to filter results"""
    




@dataclasses.dataclass
class SearchInstitutionsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    financial_institutions: Optional[shared_financialinstitutions.FinancialInstitutions] = dataclasses.field(default=None)
    r"""Financial institutions returned from a search"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

