"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import updateapplepaymerchantdomains as shared_updateapplepaymerchantdomains
from typing import Optional



@dataclasses.dataclass
class UpdateApplePayMerchantDomainsRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    update_apple_pay_merchant_domains: shared_updateapplepaymerchantdomains.UpdateApplePayMerchantDomains = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateApplePayMerchantDomainsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

