"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import card as shared_card
from ..shared import cardupdaterequest as shared_cardupdaterequest
from typing import Any, Optional



@dataclasses.dataclass
class UpdateCardRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    card_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'cardID', 'style': 'simple', 'explode': False }})
    r"""ID of the card"""
    card_update_request: shared_cardupdaterequest.CardUpdateRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateCardResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    card: Optional[shared_card.Card] = dataclasses.field(default=None)
    r"""Card updated"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    update_card_422_application_json_object: Optional[dict[str, Any]] = dataclasses.field(default=None)
    r"""The supplied card data appeared invalid or was declined by the issuer"""
    

