"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import underwriting as shared_underwriting
from ..shared import underwritingrequest as shared_underwritingrequest
from typing import Optional



@dataclasses.dataclass
class UpdateUnderwritingRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    underwriting_request: shared_underwritingrequest.UnderwritingRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateUnderwritingResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    underwriting: Optional[shared_underwriting.Underwriting] = dataclasses.field(default=None)
    r"""The underwriting details were successfully updated"""
    

