"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import file as shared_file
from ..shared import fileuploadrequest as shared_fileuploadrequest
from typing import Optional



@dataclasses.dataclass
class UploadFileRequest:
    account_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': False }})
    r"""ID of the account"""
    file_upload_request: shared_fileuploadrequest.FileUploadRequest = dataclasses.field(metadata={'request': { 'media_type': 'multipart/form-data' }})
    




@dataclasses.dataclass
class UploadFileResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    file: Optional[shared_file.File] = dataclasses.field(default=None)
    r"""File added"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

