// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/moov-go/pkg/models/shared"
	"net/http"
)

type CreateTransferOptionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Succesfully created transfer options
	CreatedTransferOptions *shared.CreatedTransferOptions
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateTransferOptionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateTransferOptionsResponse) GetCreatedTransferOptions() *shared.CreatedTransferOptions {
	if o == nil {
		return nil
	}
	return o.CreatedTransferOptions
}

func (o *CreateTransferOptionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateTransferOptionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
