// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/moov-go/pkg/models/shared"
	"net/http"
)

type GetRepresentativeRequest struct {
	// ID of the account
	AccountID string `pathParam:"style=simple,explode=false,name=accountID"`
	// ID of the representative
	RepresentativeID string `pathParam:"style=simple,explode=false,name=representativeID"`
}

func (o *GetRepresentativeRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *GetRepresentativeRequest) GetRepresentativeID() string {
	if o == nil {
		return ""
	}
	return o.RepresentativeID
}

type GetRepresentativeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The Representative
	Representative *shared.Representative
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRepresentativeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRepresentativeResponse) GetRepresentative() *shared.Representative {
	if o == nil {
		return nil
	}
	return o.Representative
}

func (o *GetRepresentativeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRepresentativeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
