// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/moov-go/pkg/models/shared"
	"net/http"
)

type ListBankAccountsRequest struct {
	// ID of the account
	AccountID string `pathParam:"style=simple,explode=false,name=accountID"`
}

func (o *ListBankAccountsRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type ListBankAccountsResponse struct {
	// Successfully retrieved bank accounts
	BankAccounts []shared.BankAccountResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListBankAccountsResponse) GetBankAccounts() []shared.BankAccountResponse {
	if o == nil {
		return nil
	}
	return o.BankAccounts
}

func (o *ListBankAccountsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListBankAccountsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListBankAccountsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
