// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type PatchTransferRequest struct {
	PatchTransfer shared.PatchTransfer `request:"mediaType=application/json"`
	// ID of a connected account
	AccountID *string `queryParam:"style=form,explode=true,name=accountID"`
	// ID of the Transfer
	TransferID string `pathParam:"style=simple,explode=false,name=transferID"`
}

func (o *PatchTransferRequest) GetPatchTransfer() shared.PatchTransfer {
	if o == nil {
		return shared.PatchTransfer{}
	}
	return o.PatchTransfer
}

func (o *PatchTransferRequest) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *PatchTransferRequest) GetTransferID() string {
	if o == nil {
		return ""
	}
	return o.TransferID
}

type PatchTransferResponse struct {
	ContentType string
	// Details of a transfer
	GetTransferFull *shared.GetTransferFull
	StatusCode      int
	RawResponse     *http.Response
}

func (o *PatchTransferResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchTransferResponse) GetGetTransferFull() *shared.GetTransferFull {
	if o == nil {
		return nil
	}
	return o.GetTransferFull
}

func (o *PatchTransferResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchTransferResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
