// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/moov-go/pkg/models/shared"
	"net/http"
)

type PostLinkApplePayTokenRequest struct {
	LinkApplePay shared.LinkApplePay `request:"mediaType=application/json"`
	// ID of the account
	AccountID string `pathParam:"style=simple,explode=false,name=accountID"`
}

func (o *PostLinkApplePayTokenRequest) GetLinkApplePay() shared.LinkApplePay {
	if o == nil {
		return shared.LinkApplePay{}
	}
	return o.LinkApplePay
}

func (o *PostLinkApplePayTokenRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type PostLinkApplePayTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Apple Pay token linked
	LinkedApplePayPaymentMethod *shared.LinkedApplePayPaymentMethod
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostLinkApplePayTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostLinkApplePayTokenResponse) GetLinkedApplePayPaymentMethod() *shared.LinkedApplePayPaymentMethod {
	if o == nil {
		return nil
	}
	return o.LinkedApplePayPaymentMethod
}

func (o *PostLinkApplePayTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostLinkApplePayTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
