// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostInitiateMicroDepositsRequest struct {
	// ID of the account
	AccountID string `pathParam:"style=simple,explode=false,name=accountID"`
	// ID of the bank account
	BankAccountID string `pathParam:"style=simple,explode=false,name=bankAccountID"`
}

func (o *PostInitiateMicroDepositsRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *PostInitiateMicroDepositsRequest) GetBankAccountID() string {
	if o == nil {
		return ""
	}
	return o.BankAccountID
}

type PostInitiateMicroDepositsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *PostInitiateMicroDepositsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostInitiateMicroDepositsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostInitiateMicroDepositsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
