// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/moov-go/pkg/models/shared"
	"net/http"
)

type UploadFileRequest struct {
	FileUploadRequest shared.FileUploadRequest `request:"mediaType=multipart/form-data"`
	// ID of the account
	AccountID string `pathParam:"style=simple,explode=false,name=accountID"`
}

func (o *UploadFileRequest) GetFileUploadRequest() shared.FileUploadRequest {
	if o == nil {
		return shared.FileUploadRequest{}
	}
	return o.FileUploadRequest
}

func (o *UploadFileRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type UploadFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File added
	File *shared.File
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UploadFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UploadFileResponse) GetFile() *shared.File {
	if o == nil {
		return nil
	}
	return o.File
}

func (o *UploadFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UploadFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
