// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// HolderType - The type of holder on a funding source
type HolderType string

const (
	HolderTypeIndividual HolderType = "individual"
	HolderTypeBusiness   HolderType = "business"
)

func (e HolderType) ToPointer() *HolderType {
	return &e
}

func (e *HolderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "individual":
		fallthrough
	case "business":
		*e = HolderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HolderType: %v", v)
	}
}
