// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AuthorizedUser - Fields to identify a human
type AuthorizedUser struct {
	BirthDateProvided *bool   `json:"birthDateProvided,omitempty"`
	FirstName         *string `json:"firstName,omitempty"`
	LastName          *string `json:"lastName,omitempty"`
}

func (o *AuthorizedUser) GetBirthDateProvided() *bool {
	if o == nil {
		return nil
	}
	return o.BirthDateProvided
}

func (o *AuthorizedUser) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *AuthorizedUser) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}
