// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BankAccount - Describes the account to link to the Moov account
type BankAccount struct {
	// Describes the account to link to the Moov account
	Account *BankAccountIntegration `json:"account,omitempty"`
}

func (o *BankAccount) GetAccount() *BankAccountIntegration {
	if o == nil {
		return nil
	}
	return o.Account
}
