// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type BankAccountPayloadType string

const (
	BankAccountPayloadTypeBankAccount BankAccountPayloadType = "BankAccount"
	BankAccountPayloadTypePlaid       BankAccountPayloadType = "Plaid"
	BankAccountPayloadTypePlaidLink   BankAccountPayloadType = "PlaidLink"
	BankAccountPayloadTypeMx          BankAccountPayloadType = "MX"
)

type BankAccountPayload struct {
	BankAccount *BankAccount
	Plaid       *Plaid
	PlaidLink   *PlaidLink
	Mx          *Mx

	Type BankAccountPayloadType
}

func CreateBankAccountPayloadBankAccount(bankAccount BankAccount) BankAccountPayload {
	typ := BankAccountPayloadTypeBankAccount

	return BankAccountPayload{
		BankAccount: &bankAccount,
		Type:        typ,
	}
}

func CreateBankAccountPayloadPlaid(plaid Plaid) BankAccountPayload {
	typ := BankAccountPayloadTypePlaid

	return BankAccountPayload{
		Plaid: &plaid,
		Type:  typ,
	}
}

func CreateBankAccountPayloadPlaidLink(plaidLink PlaidLink) BankAccountPayload {
	typ := BankAccountPayloadTypePlaidLink

	return BankAccountPayload{
		PlaidLink: &plaidLink,
		Type:      typ,
	}
}

func CreateBankAccountPayloadMx(mx Mx) BankAccountPayload {
	typ := BankAccountPayloadTypeMx

	return BankAccountPayload{
		Mx:   &mx,
		Type: typ,
	}
}

func (u *BankAccountPayload) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	bankAccount := new(BankAccount)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&bankAccount); err == nil {
		u.BankAccount = bankAccount
		u.Type = BankAccountPayloadTypeBankAccount
		return nil
	}

	plaid := new(Plaid)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&plaid); err == nil {
		u.Plaid = plaid
		u.Type = BankAccountPayloadTypePlaid
		return nil
	}

	plaidLink := new(PlaidLink)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&plaidLink); err == nil {
		u.PlaidLink = plaidLink
		u.Type = BankAccountPayloadTypePlaidLink
		return nil
	}

	mx := new(Mx)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&mx); err == nil {
		u.Mx = mx
		u.Type = BankAccountPayloadTypeMx
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u BankAccountPayload) MarshalJSON() ([]byte, error) {
	if u.BankAccount != nil {
		return json.Marshal(u.BankAccount)
	}

	if u.Plaid != nil {
		return json.Marshal(u.Plaid)
	}

	if u.PlaidLink != nil {
		return json.Marshal(u.PlaidLink)
	}

	if u.Mx != nil {
		return json.Marshal(u.Mx)
	}

	return nil, errors.New("could not marshal union type: all fields are null")

}
