// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CapabilityRequestError - Error response for http requests that failed
type CapabilityRequestError struct {
	Error *string `json:"error,omitempty"`
}

func (o *CapabilityRequestError) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
