// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CapabilityStatus - The status of the capability requested for an account
type CapabilityStatus string

const (
	CapabilityStatusEnabled  CapabilityStatus = "enabled"
	CapabilityStatusDisabled CapabilityStatus = "disabled"
	CapabilityStatusPending  CapabilityStatus = "pending"
)

func (e CapabilityStatus) ToPointer() *CapabilityStatus {
	return &e
}

func (e *CapabilityStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enabled":
		fallthrough
	case "disabled":
		fallthrough
	case "pending":
		*e = CapabilityStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CapabilityStatus: %v", v)
	}
}
