// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CardRequest - Describes the card to link to the Moov account
type CardRequest struct {
	BillingAddress *Address `json:"billingAddress,omitempty"`
	CardCvv        *string  `json:"cardCvv,omitempty"`
	CardNumber     *string  `json:"cardNumber,omitempty"`
	// Indicates cardholder has authorized card to be stored for future payments
	CardOnFile *bool `json:"cardOnFile,omitempty"`
	// The expiration date of the linked card or token
	Expiration *CardExpiration `json:"expiration,omitempty"`
	HolderName *string         `json:"holderName,omitempty"`
	// Moov account ID of the merchant or entity authorized to store the card. Defaults to your platform account ID if cardOnFile is set to true and no other account is provided
	MerchantAccountID *string `json:"merchantAccountID,omitempty"`
}

func (o *CardRequest) GetBillingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.BillingAddress
}

func (o *CardRequest) GetCardCvv() *string {
	if o == nil {
		return nil
	}
	return o.CardCvv
}

func (o *CardRequest) GetCardNumber() *string {
	if o == nil {
		return nil
	}
	return o.CardNumber
}

func (o *CardRequest) GetCardOnFile() *bool {
	if o == nil {
		return nil
	}
	return o.CardOnFile
}

func (o *CardRequest) GetExpiration() *CardExpiration {
	if o == nil {
		return nil
	}
	return o.Expiration
}

func (o *CardRequest) GetHolderName() *string {
	if o == nil {
		return nil
	}
	return o.HolderName
}

func (o *CardRequest) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}
