// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// CardAccountUpdater - The results of the most recent card update request
type CardAccountUpdater struct {
	// The results of the card update request
	UpdateType *CardUpdateReason `json:"updateType,omitempty"`
	UpdatedOn  *time.Time        `json:"updatedOn,omitempty"`
}

func (o *CardAccountUpdater) GetUpdateType() *CardUpdateReason {
	if o == nil {
		return nil
	}
	return o.UpdateType
}

func (o *CardAccountUpdater) GetUpdatedOn() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedOn
}
