// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/moov-go/pkg/types"
	"github.com/speakeasy-sdks/moov-go/pkg/utils"
)

type CompleteMicroDepositsResponse struct {
	// The micro-deposit status
	status *string `const:"verified" json:"status,omitempty"`
}

func (c CompleteMicroDepositsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompleteMicroDepositsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CompleteMicroDepositsResponse) GetStatus() *string {
	return types.String("verified")
}
