// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateTransferDestination - A payment method ID
type CreateTransferDestination struct {
	AchDetails *CreateACHDetailsBase `json:"achDetails,omitempty"`
	// UUID v4
	PaymentMethodID *string `json:"paymentMethodID,omitempty"`
}

func (o *CreateTransferDestination) GetAchDetails() *CreateACHDetailsBase {
	if o == nil {
		return nil
	}
	return o.AchDetails
}

func (o *CreateTransferDestination) GetPaymentMethodID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentMethodID
}

// CreateTransferSource - A payment method ID
type CreateTransferSource struct {
	AchDetails  *CreateAchDetailsSource `json:"achDetails,omitempty"`
	CardDetails *CreateCardDetails      `json:"cardDetails,omitempty"`
	// UUID v4
	PaymentMethodID *string `json:"paymentMethodID,omitempty"`
	// UUID v4
	TransferID *string `json:"transferID,omitempty"`
}

func (o *CreateTransferSource) GetAchDetails() *CreateAchDetailsSource {
	if o == nil {
		return nil
	}
	return o.AchDetails
}

func (o *CreateTransferSource) GetCardDetails() *CreateCardDetails {
	if o == nil {
		return nil
	}
	return o.CardDetails
}

func (o *CreateTransferSource) GetPaymentMethodID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentMethodID
}

func (o *CreateTransferSource) GetTransferID() *string {
	if o == nil {
		return nil
	}
	return o.TransferID
}

type CreateTransfer struct {
	// A representation of money containing an integer value and it's currency.
	Amount *Amount `json:"amount,omitempty"`
	// A description of the transfer
	Description *string `json:"description,omitempty"`
	// A payment method ID
	Destination *CreateTransferDestination `json:"destination,omitempty"`
	// Total or markup fee
	FacilitatorFee *CreateFacilitatorFee `json:"facilitatorFee,omitempty"`
	// Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
	Metadata map[string]string `json:"metadata,omitempty"`
	// A payment method ID
	Source *CreateTransferSource `json:"source,omitempty"`
}

func (o *CreateTransfer) GetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CreateTransfer) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTransfer) GetDestination() *CreateTransferDestination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *CreateTransfer) GetFacilitatorFee() *CreateFacilitatorFee {
	if o == nil {
		return nil
	}
	return o.FacilitatorFee
}

func (o *CreateTransfer) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *CreateTransfer) GetSource() *CreateTransferSource {
	if o == nil {
		return nil
	}
	return o.Source
}
