// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateApplePaySession struct {
	// A string of 64 or fewer UTF-8 characters. Displayed in the Buy button.
	//
	DisplayName string `json:"displayName"`
	Domain      string `json:"domain"`
}

func (o *CreateApplePaySession) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *CreateApplePaySession) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}
