// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateReversal struct {
	// Amount to reverse in cents. If null, the original transfer's full amount will be reversed. Partial amounts will automatically trigger a refund instead of a cancellation.
	Amount *int64 `json:"amount,omitempty"`
}

func (o *CreateReversal) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}
