// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// CreatedTransfer - A transfer was successfully created but an error occurred while generating the synchronous response. The asynchronous response object will be returned.
type CreatedTransfer struct {
	CreatedOn *time.Time `json:"createdOn,omitempty"`
	// ID of Transfer
	TransferID *string `json:"transferID,omitempty"`
}

func (o *CreatedTransfer) GetCreatedOn() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedOn
}

func (o *CreatedTransfer) GetTransferID() *string {
	if o == nil {
		return nil
	}
	return o.TransferID
}
