// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/moov-go/pkg/utils"
)

// CreateRepresentativeAddress - Residential address for an individual. Business addresses not accepted.
type CreateRepresentativeAddress struct {
	AddressLine1    *string `json:"addressLine1,omitempty"`
	AddressLine2    *string `json:"addressLine2,omitempty"`
	City            *string `json:"city,omitempty"`
	Country         *string `json:"country,omitempty"`
	PostalCode      *string `json:"postalCode,omitempty"`
	StateOrProvince *string `json:"stateOrProvince,omitempty"`
}

func (o *CreateRepresentativeAddress) GetAddressLine1() *string {
	if o == nil {
		return nil
	}
	return o.AddressLine1
}

func (o *CreateRepresentativeAddress) GetAddressLine2() *string {
	if o == nil {
		return nil
	}
	return o.AddressLine2
}

func (o *CreateRepresentativeAddress) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *CreateRepresentativeAddress) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *CreateRepresentativeAddress) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *CreateRepresentativeAddress) GetStateOrProvince() *string {
	if o == nil {
		return nil
	}
	return o.StateOrProvince
}

// CreateRepresentativeBirthDate - Birthdate for an individual
type CreateRepresentativeBirthDate struct {
	Day   int64 `json:"day"`
	Month int64 `json:"month"`
	Year  int64 `json:"year"`
}

func (o *CreateRepresentativeBirthDate) GetDay() int64 {
	if o == nil {
		return 0
	}
	return o.Day
}

func (o *CreateRepresentativeBirthDate) GetMonth() int64 {
	if o == nil {
		return 0
	}
	return o.Month
}

func (o *CreateRepresentativeBirthDate) GetYear() int64 {
	if o == nil {
		return 0
	}
	return o.Year
}

type Itin struct {
	Full     *string `json:"full,omitempty"`
	LastFour *string `json:"lastFour,omitempty"`
}

func (o *Itin) GetFull() *string {
	if o == nil {
		return nil
	}
	return o.Full
}

func (o *Itin) GetLastFour() *string {
	if o == nil {
		return nil
	}
	return o.LastFour
}

type Ssn struct {
	Full     *string `json:"full,omitempty"`
	LastFour *string `json:"lastFour,omitempty"`
}

func (o *Ssn) GetFull() *string {
	if o == nil {
		return nil
	}
	return o.Full
}

func (o *Ssn) GetLastFour() *string {
	if o == nil {
		return nil
	}
	return o.LastFour
}

type GovernmentID struct {
	Itin *Itin `json:"itin,omitempty"`
	Ssn  *Ssn  `json:"ssn,omitempty"`
}

func (o *GovernmentID) GetItin() *Itin {
	if o == nil {
		return nil
	}
	return o.Itin
}

func (o *GovernmentID) GetSsn() *Ssn {
	if o == nil {
		return nil
	}
	return o.Ssn
}

// CreateRepresentativeName - Name for an individual
type CreateRepresentativeName struct {
	// Name this person was given. This is usually the the same as first name.
	FirstName string `json:"firstName"`
	// Family name of this person. This is usually the the same as last name.
	LastName string `json:"lastName"`
	// Name this person was given. This is usually the the same as first name.
	MiddleName *string `json:"middleName,omitempty"`
	// Suffix of a given name
	Suffix *string `json:"suffix,omitempty"`
}

func (o *CreateRepresentativeName) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *CreateRepresentativeName) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *CreateRepresentativeName) GetMiddleName() *string {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *CreateRepresentativeName) GetSuffix() *string {
	if o == nil {
		return nil
	}
	return o.Suffix
}

type CreateRepresentativePhone struct {
	CountryCode *string `json:"countryCode,omitempty"`
	Number      *string `json:"number,omitempty"`
}

func (o *CreateRepresentativePhone) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *CreateRepresentativePhone) GetNumber() *string {
	if o == nil {
		return nil
	}
	return o.Number
}

// Responsibilities - Describes the job responsibilities of an individual
type Responsibilities struct {
	// Indicates whether this individual has significant management responsibilities within the business
	IsController *bool `default:"false" json:"isController"`
	// If `true`, this field indicates that this individual has an ownership stake of at least 25% in the business. If the representative does not own at least 25% of the business, this field should be `false`.
	IsOwner  *bool  `default:"false" json:"isOwner"`
	JobTitle string `json:"jobTitle"`
	// The percentage of ownership this individual has in the business (required if `isOwner` is `true`)
	OwnershipPercentage int64 `json:"ownershipPercentage"`
}

func (r Responsibilities) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Responsibilities) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Responsibilities) GetIsController() *bool {
	if o == nil {
		return nil
	}
	return o.IsController
}

func (o *Responsibilities) GetIsOwner() *bool {
	if o == nil {
		return nil
	}
	return o.IsOwner
}

func (o *Responsibilities) GetJobTitle() string {
	if o == nil {
		return ""
	}
	return o.JobTitle
}

func (o *Responsibilities) GetOwnershipPercentage() int64 {
	if o == nil {
		return 0
	}
	return o.OwnershipPercentage
}

// CreateRepresentative - Describes the fields available when creating a representative
type CreateRepresentative struct {
	// Residential address for an individual. Business addresses not accepted.
	Address   *CreateRepresentativeAddress   `json:"address,omitempty"`
	BirthDate *CreateRepresentativeBirthDate `json:"birthDate,omitempty"`
	// Email Address
	Email            *string                    `json:"email,omitempty"`
	GovernmentID     *GovernmentID              `json:"governmentID,omitempty"`
	Name             *CreateRepresentativeName  `json:"name,omitempty"`
	Phone            *CreateRepresentativePhone `json:"phone,omitempty"`
	Responsibilities *Responsibilities          `json:"responsibilities,omitempty"`
}

func (o *CreateRepresentative) GetAddress() *CreateRepresentativeAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *CreateRepresentative) GetBirthDate() *CreateRepresentativeBirthDate {
	if o == nil {
		return nil
	}
	return o.BirthDate
}

func (o *CreateRepresentative) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateRepresentative) GetGovernmentID() *GovernmentID {
	if o == nil {
		return nil
	}
	return o.GovernmentID
}

func (o *CreateRepresentative) GetName() *CreateRepresentativeName {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateRepresentative) GetPhone() *CreateRepresentativePhone {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *CreateRepresentative) GetResponsibilities() *Responsibilities {
	if o == nil {
		return nil
	}
	return o.Responsibilities
}
