// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/moov-go/pkg/utils"
)

type Ein struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Number               *string                `json:"number,omitempty"`
}

func (e Ein) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Ein) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Ein) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Ein) GetNumber() *string {
	if o == nil {
		return nil
	}
	return o.Number
}
