// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnrichedBusiness - Describes a company
type EnrichedBusiness struct {
	Address *Address `json:"address,omitempty"`
	// Email Address
	Email *string `json:"email,omitempty"`
	// Describes industry specific identifiers
	IndustryCodes     *EnrichedIndustryCodes `json:"industryCodes,omitempty"`
	LegalBusinessName *string                `json:"legalBusinessName,omitempty"`
	Phone             *Phone                 `json:"phone,omitempty"`
	Website           *string                `json:"website,omitempty"`
}

func (o *EnrichedBusiness) GetAddress() *Address {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *EnrichedBusiness) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *EnrichedBusiness) GetIndustryCodes() *EnrichedIndustryCodes {
	if o == nil {
		return nil
	}
	return o.IndustryCodes
}

func (o *EnrichedBusiness) GetLegalBusinessName() *string {
	if o == nil {
		return nil
	}
	return o.LegalBusinessName
}

func (o *EnrichedBusiness) GetPhone() *Phone {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *EnrichedBusiness) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}
