// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FileUploadRequestFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *FileUploadRequestFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *FileUploadRequestFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

// FileUploadRequest - Request to attach a file to an account.
type FileUploadRequest struct {
	// The file to be added. Valid types are [csv, png, jpeg, pdf].
	File FileUploadRequestFile `multipartForm:"file"`
	// The file purpose
	FilePurpose FilePurpose `multipartForm:"name=filePurpose"`
}

func (o *FileUploadRequest) GetFile() FileUploadRequestFile {
	if o == nil {
		return FileUploadRequestFile{}
	}
	return o.File
}

func (o *FileUploadRequest) GetFilePurpose() FilePurpose {
	if o == nil {
		return FilePurpose("")
	}
	return o.FilePurpose
}
