// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PaymentMethodWalletWallet - A Moov wallet to store funds for transfers.
type PaymentMethodWalletWallet struct {
	// UUID v4
	WalletID *string `json:"walletID,omitempty"`
}

func (o *PaymentMethodWalletWallet) GetWalletID() *string {
	if o == nil {
		return nil
	}
	return o.WalletID
}

// PaymentMethodWallet - A method of moving money that is a Moov wallet
type PaymentMethodWallet struct {
	// UUID v4
	PaymentMethodID *string `json:"paymentMethodID,omitempty"`
	// The payment method type that represents a payment rail and directionality
	PaymentMethodType *PaymentMethodsType        `json:"paymentMethodType,omitempty"`
	Wallet            *PaymentMethodWalletWallet `json:"wallet,omitempty"`
}

func (o *PaymentMethodWallet) GetPaymentMethodID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentMethodID
}

func (o *PaymentMethodWallet) GetPaymentMethodType() *PaymentMethodsType {
	if o == nil {
		return nil
	}
	return o.PaymentMethodType
}

func (o *PaymentMethodWallet) GetWallet() *PaymentMethodWalletWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}
