// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TermsOfServiceToken - An encrypted value used to record acceptance of Moov's Terms of Service
type TermsOfServiceToken struct {
	Token *string `json:"token,omitempty"`
}

func (o *TermsOfServiceToken) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}
