// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// UnderwritingStatus - The status of underwriting for an account
type UnderwritingStatus string

const (
	UnderwritingStatusApproved      UnderwritingStatus = "approved"
	UnderwritingStatusRejected      UnderwritingStatus = "rejected"
	UnderwritingStatusPendingReview UnderwritingStatus = "pendingReview"
	UnderwritingStatusPending       UnderwritingStatus = "pending"
	UnderwritingStatusNotRequested  UnderwritingStatus = "notRequested"
)

func (e UnderwritingStatus) ToPointer() *UnderwritingStatus {
	return &e
}

func (e *UnderwritingStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "approved":
		fallthrough
	case "rejected":
		fallthrough
	case "pendingReview":
		fallthrough
	case "pending":
		fallthrough
	case "notRequested":
		*e = UnderwritingStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnderwritingStatus: %v", v)
	}
}
