// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// WalletTransactionStatus - Wallet transaction status
type WalletTransactionStatus string

const (
	WalletTransactionStatusPending   WalletTransactionStatus = "pending"
	WalletTransactionStatusCompleted WalletTransactionStatus = "completed"
	WalletTransactionStatusCanceled  WalletTransactionStatus = "canceled"
	WalletTransactionStatusFailed    WalletTransactionStatus = "failed"
)

func (e WalletTransactionStatus) ToPointer() *WalletTransactionStatus {
	return &e
}

func (e *WalletTransactionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "completed":
		fallthrough
	case "canceled":
		fallthrough
	case "failed":
		*e = WalletTransactionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WalletTransactionStatus: %v", v)
	}
}
