// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Wallet - A Moov wallet to store funds for transfers.
type Wallet struct {
	// A representation of money containing an integer value and it's currency.
	AvailableBalance *Amount `json:"availableBalance,omitempty"`
	// UUID v4
	WalletID *string `json:"walletID,omitempty"`
}

func (o *Wallet) GetAvailableBalance() *Amount {
	if o == nil {
		return nil
	}
	return o.AvailableBalance
}

func (o *Wallet) GetWalletID() *string {
	if o == nil {
		return nil
	}
	return o.WalletID
}
