"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import achexception as shared_achexception
from ..shared import achstatus as shared_achstatus
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ACHDetailsBase:
    r"""ACH specific details about the transaction"""
    status: shared_achstatus.ACHStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""ACH status"""
    trace_number: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('traceNumber') }})
    company_entry_description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('companyEntryDescription'), 'exclude': lambda f: f is None }})
    r"""An optional override of the default NACHA Company Entry Description for a transfer."""
    correction: Optional[shared_achexception.ACHException] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('correction'), 'exclude': lambda f: f is None }})
    originating_company_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('originatingCompanyName'), 'exclude': lambda f: f is None }})
    r"""An optional override of the default NACHA Company Name for a transfer."""
    return_: Optional[shared_achexception.ACHException] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('return'), 'exclude': lambda f: f is None }})
    

