"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ACHStatus(str, Enum):
    r"""ACH status"""
    INITIATED = 'initiated'
    ORIGINATED = 'originated'
    CORRECTED = 'corrected'
    RETURNED = 'returned'
    COMPLETED = 'completed'
