"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import authorizationspendlimitcontrol as shared_authorizationspendlimitcontrol
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class AuthorizationControls:
    spend_limits: Optional[list[shared_authorizationspendlimitcontrol.AuthorizationSpendLimitControl]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('spendLimits'), 'exclude': lambda f: f is None }})
    

