"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from petstore import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class BirthDate:
    r"""Birthdate for an individual"""
    day: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('day') }})
    month: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('month') }})
    year: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('year') }})
    

