"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import cardfailurecode as shared_cardfailurecode
from ..shared import cardstatus as shared_cardstatus
from ..shared import transactionsource as shared_transactionsource
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CardDetails:
    dynamic_descriptor: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dynamicDescriptor'), 'exclude': lambda f: f is None }})
    r"""An optional override of the default card statement descriptor for a transfer."""
    failure_code: Optional[shared_cardfailurecode.CardFailureCode] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('failureCode'), 'exclude': lambda f: f is None }})
    status: Optional[shared_cardstatus.CardStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""Card status"""
    transaction_source: Optional[shared_transactionsource.TransactionSource] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactionSource'), 'exclude': lambda f: f is None }})
    r"""Describes how the card transaction was initiated"""
    

