"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CardStatus(str, Enum):
    r"""Card status"""
    INITIATED = 'initiated'
    CONFIRMED = 'confirmed'
    CANCELED = 'canceled'
    SETTLED = 'settled'
    FAILED = 'failed'
    COMPLETED = 'completed'
