"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from petstore import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class Countries:
    r"""The Countries of operation for an account"""
    countries: list[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('countries') }})
    

