"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class IssuedCardType(str, Enum):
    r"""Type of a Moov issued card"""
    SINGLE_USE = 'single-use'
