"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PlaidLinkIntegration:
    r"""This is used by Moov.js with a Plaid reseller relationship. The details of a Plaid link integration for a linked funding source. <br><br> `sandbox` - (requires Plaid Reseller setup with Moov) When linking a bank account to a `sandbox` account using a Plaid public token it will utilize Plaid's sandbox environment. The Plaid public token provided must be generated from Plaid's sandbox environment. Please see <a href=\\"https://plaid.com/docs/api/sandbox/#sandboxpublic_tokencreate\\" target=\\"_blank\\">Plaid's sandbox documentation</a> for more details."""
    public_token: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('publicToken'), 'exclude': lambda f: f is None }})
    

