"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class RefundCardStatus(str, Enum):
    r"""Card status for refunds"""
    INITIATED = 'initiated'
    CONFIRMED = 'confirmed'
    SETTLED = 'settled'
    FAILED = 'failed'
    COMPLETED = 'completed'
