"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import requirementerrorcode as shared_requirementerrorcode
from ..shared import requirementid as shared_requirementid
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RequirementError:
    r"""Describes an error fulfilling a Requirement"""
    error_code: Optional[shared_requirementerrorcode.RequirementErrorCode] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorCode'), 'exclude': lambda f: f is None }})
    requirement: Optional[shared_requirementid.RequirementID] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('requirement'), 'exclude': lambda f: f is None }})
    r"""The unique ID of what the requirement is asking to be filled out."""
    

