"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import authorizationcontrols as shared_authorizationcontrols
from ..shared import createauthorizeduser as shared_createauthorizeduser
from ..shared import issuedcardstate as shared_issuedcardstate
from dataclasses_json import Undefined, dataclass_json
from petstore import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class UpdateIssuedCard:
    authorization_controls: Optional[shared_authorizationcontrols.AuthorizationControls] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authorizationControls'), 'exclude': lambda f: f is None }})
    authorized_user: Optional[shared_createauthorizeduser.CreateAuthorizedUser] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authorizedUser'), 'exclude': lambda f: f is None }})
    r"""Fields to identify a human"""
    memo: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('memo'), 'exclude': lambda f: f is None }})
    r"""Optional descriptive name"""
    state: Optional[shared_issuedcardstate.IssuedCardState] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('state'), 'exclude': lambda f: f is None }})
    r"""State of a Moov issued card"""
    

